<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5pmv5Yy65LuL57uN');
$cfg_Cs[2]=array(0,1,1,'5pmv5Yy66LWE6K6v');
$cfg_Cs[3]=array(0,1,1,'5ri46K6w5pS755Wl');
$cfg_Cs[5]=array(3,1,1,'5ZCD');
$cfg_Cs[6]=array(3,1,1,'5L2P');
$cfg_Cs[7]=array(3,1,1,'6KGM');
$cfg_Cs[8]=array(3,1,1,'5ri4');
$cfg_Cs[9]=array(3,1,1,'6LSt');
$cfg_Cs[10]=array(3,1,1,'5aix');
$cfg_Cs[11]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[15]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[16]=array(0,1,1,'5ZWG5Yqh5ZCI5L2c');
$cfg_Cs[14]=array(0,1,1,'5pmv54K5566A5LuL');
$cfg_Cs[17]=array(0,1,1,'5bm754Gv54mH');
?>