<li>
          <table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tbody>
              <tr>
                <td width="12%"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="82" height="80"></a></td>
                <td width="88%" valign="top"><a href="[field:arcurl/]">
                  <p class="c_blue">[field:title/]</p>
                  <p class="f_12">[field:description/]</p>
                  </a></td>
              </tr>
            </tbody>
          </table>
        </li>