<li>
          <table width="99%" border="0" cellpadding="0" cellspacing="0">
            <tbody>
              <tr>
                <td width="37%"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="282" height="160"></a></td>
                <td width="63%" valign="top" style="padding-top:20px;"><div><span class="f_20 c_blue"><a href="[field:arcurl/]">[field:title/] </a></span> <span class="mp "><a href="#">门票价格</a></span> <span class="you"><a href="#">虚拟游</a></span></div>
                  <div>[field:description/]......</div></td>
              </tr>
            </tbody>
          </table>
        </li>