<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> <span>|</span> ",1355,1460);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[1]=Array("global","",1509,1535);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",1638,1662);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",2024,2045);
$z[3][4]=array();
$z[3][4]['name']="cfg_zx";
$z[4]=Array("global","",2093,2114);
$z[4][4]=array();
$z[4][4]['name']="cfg_yy";
$z[5]=Array("global","",2162,2183);
$z[5][4]=array();
$z[5][4]['name']="cfg_ts";
$z[6]=Array("global","",2479,2500);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2519,2540);
$z[7][4]=array();
$z[7][4]['name']="cfg_qq";

?>