<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> <span>|</span> ",1355,1460);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[1]=Array("global","",1621,1645);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",2007,2028);
$z[2][4]=array();
$z[2][4]['name']="cfg_zx";
$z[3]=Array("global","",2076,2097);
$z[3][4]=array();
$z[3][4]['name']="cfg_yy";
$z[4]=Array("global","",2145,2166);
$z[4][4]=array();
$z[4][4]['name']="cfg_ts";
$z[5]=Array("global","",2462,2483);
$z[5][4]=array();
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",2502,2523);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";

?>