<?php
$z[0]=Array("global","",1336,1356);
$z[0][4]=array();
$z[0][4]['name']="youjt";
$z[1]=Array("global","",1409,1429);
$z[1][4]=array();
$z[1][4]['name']="youmt";
$z[2]=Array("global","",1482,1502);
$z[2][4]=array();
$z[2][4]['name']="youht";
$z[3]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <div class=\"subnav\">\r\n          <div>{dede:channel type='son'} <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </div>\r\n        </div>\r\n      </li>\r\n      ",1831,2230);
$z[3][4]=array();
$z[3][4]['typeid']="{dede:field.typeid/";

?>