<?php
$z[0]=Array("global","",219,245);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1066,1105);
$z[1][4]=array();
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("field","",1402,1431);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("global","",1774,1799);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",2301,2629);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[5]=Array("field","",2799,2820);
$z[5][4]=array();
$z[5][4]['name']="content";
$z[6]=Array("include","",2875,2914);
$z[6][4]=array();
$z[6][4]['filename']="footer_m.htm";

?>