<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-12-06 09:35:20
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-12-06 09:35:57
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-12-06 09:36:51
*/
?>
